### ISSUE TITLE
fix console error when delete group

### ISSUE THREAD

**Issue by yclim** [yclim/gem#121]
![image](https://user-images.githubusercontent.com/4500007/80618344-cfc7b580-8a75-11ea-98ce-5aa26dc587ba.png)

**Comment by neojunjie** [comment]
any way to replicate the bug?

**Comment by neojunjie** [comment]
Add more error messages here

09:12:01.648 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at innohack.gem.service.MatchService.removeAllAssociatedRuleFromCache(MatchService.java:151)
	at innohack.gem.service.MatchService.onUpdateGroupRule(MatchService.java:144)
	at innohack.gem.service.MatchService.onUpdateEvent(MatchService.java:43)
	at innohack.gem.service.GroupService.deleteGroup(GroupService.java:50)
	at innohack.gem.web.GroupController.deleteGroup(GroupController.java:39)
